music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only:[:create, :new, :show]
  resource :session, only:[:create, :new, :destroy]
end

music_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

music_app/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#

class User < ActiveRecord::Base
  after_initialize :ensure_session_token
  validates :email, uniqueness: true, presence: true
  validates :session_token, presence: true
  validates :password_digest, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  attr_reader :password

  def self.generate_session_token
    SecureRandom.urlsafe_base64(16)
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    if user
      return user if user.is_password?(password)
    end
    nil
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end
end

music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :logged_in?
  helper_method :log_in!
  helper_method :current_user

  private
  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def log_in!(user)
    session[:session_token] = user.reset_session_token!
  end

  def logged_in?(user)
    user.session_token == session[:session_token]
  end
end

music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    session[:session_token] = nil
    render :new
  end

  def create
    user = User.find_by_credentials(params[:user][:email], params[:user][:password])

    if user.nil?
      flash.now[:errors] = ['incorrect login info']
      render :new
    else
      log_in!(user)
      redirect_to user_url(user)
    end
  end

  def destroy
    session[:session_token] = nil
    render :new
  end
end

music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in!(@user)
      redirect_to new_session_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    render :show
  end

  private
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

music_app/app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    "<input
      type='hidden'
      name='authenticity_token'
      value='#{form_authenticity_token}'>".html_safe
  end
end

music_app/app/helpers/sessions_helper.rb
module SessionsHelper
end

music_app/app/helpers/users_helper.rb
module UsersHelper
end

music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <h6>
    <% if current_user && logged_in?(current_user)%>
      <a href= <%= SessionsController/destroy %> >Click Here to Log Out</a>
    <% else %>
      <a href= <%= new_session_url %> >Click Here to Log In</a>
    <% end %>

  </h1>
  <% if flash[:errors] %>
    <ul>
    <% flash[:errors].each do |error|%>
      <li><%= error %></li>
    <% end %>
    </ul>
  <% end %>

  <body>
    <%= yield %>
  </body>
</html>

music_app/app/views/users/new.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <title>User setup</title>
  </head>
  <body>
    <form action="<%= users_url %>" method="post">
      <%= auth_token %>
      <label for="user_email">Email: </label>
      <input type="text"
             name="user[email]"
             id="user_email"
      <br>
      <br>
      <label for="user_password">Password: </label>
      <input type="password"
             name="user[password]"
             id="user_password"
      <br>

      <input type="submit" value = "submit">
</form>

  </body>
</html>

music_app/app/views/users/show.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>User</title>
  </head>
  <body>
      <%= current_user.email %>
  </body>
</html>